# This file was generated by Nuitka

# Stubs included by default
from animo_retarget_npz import *
from automatic_bone_mapping import *
from adjust_arm_space import *


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import copy
import typing
import numpy
import transformations
import json
import unicodedata
import ntpath
import mathutils
import bpy
import functools
import pathlib
import logging
import dataclasses
import requests
import math