export interface HardwiredCommandDefinition {
  key: string;
  phrases: string[];
  action: string;
  description: string;
  offlineCapable: boolean;
}

export const HARDWIRED_COMMANDS: HardwiredCommandDefinition[] = [
  {
    key: "work_mode",
    phrases: ["work mode"],
    action: "switch_mode_work",
    description: "Switch Gail into Work Mode.",
    offlineCapable: true,
  },
  {
    key: "private_mode",
    phrases: ["private mode"],
    action: "switch_mode_private",
    description: "Switch Gail into Private Mode.",
    offlineCapable: true,
  },
  {
    key: "private_counselor_mode",
    phrases: ["vera mode", "be vera", "switch to vera", "counselor mode", "private counselor mode"],
    action: "switch_private_persona_counselor",
    description: "Switch Gail's private persona to Vera.",
    offlineCapable: true,
  },
  {
    key: "private_girlfriend_mode",
    phrases: [
      "cherry mode",
      "be cherry",
      "switch to cherry",
      "girlfriend mode",
      "private girlfriend mode",
      "switch to explicit",
      "explicit mode",
      "go explicit",
      "adult mode",
      "doc im lonley",
      "doc i'm lonely",
    ],
    action: "switch_private_persona_girlfriend",
    description: "Switch Gail's private persona to Cherry.",
    offlineCapable: true,
  },
  {
    key: "show_tasks",
    phrases: ["show tasks"],
    action: "open_tasks",
    description: "Open the task surface.",
    offlineCapable: true,
  },
  {
    key: "backup_now",
    phrases: ["backup now"],
    action: "run_backup_now",
    description: "Trigger a manual backup.",
    offlineCapable: true,
  },
  {
    key: "open_build_control_tower",
    phrases: ["open build control tower"],
    action: "open_build_control_tower",
    description: "Open the build control tower screen.",
    offlineCapable: true,
  },
  {
    key: "show_approval_queue",
    phrases: ["show approval queue"],
    action: "show_build_approval_queue",
    description: "Show pending build approvals.",
    offlineCapable: true,
  },
  {
    key: "run_script",
    phrases: ["run script"],
    action: "run_build_script",
    description: "Run a build script from the registry.",
    offlineCapable: false,
  },
  {
    key: "show_latest_results",
    phrases: ["show latest results"],
    action: "show_build_results",
    description: "Open latest build script and artifact results.",
    offlineCapable: true,
  },
  {
    key: "capture_build_screenshot",
    phrases: ["capture build screenshot"],
    action: "capture_build_screenshot",
    description: "Capture screenshot evidence for current build step.",
    offlineCapable: false,
  },
  {
    key: "analyze_current_screen",
    phrases: ["analyze current screen"],
    action: "analyze_build_screenshot",
    description: "Run screenshot analysis on current screen evidence.",
    offlineCapable: false,
  },
  {
    key: "request_changes",
    phrases: ["request changes"],
    action: "request_build_changes",
    description: "Return a build step for revision with review notes.",
    offlineCapable: true,
  },
  {
    key: "approve_step",
    phrases: ["approve step"],
    action: "approve_build_step",
    description: "Approve the selected build step for promotion.",
    offlineCapable: true,
  },
  {
    key: "show_pending_changes",
    phrases: ["show pending changes"],
    action: "show_pending_changes",
    description: "Show all pending governance changes.",
    offlineCapable: true,
  },
  {
    key: "show_last_approved_change",
    phrases: ["show last approved change"],
    action: "show_last_approved_change",
    description: "Show the most recently approved change.",
    offlineCapable: true,
  },
  {
    key: "why_was_this_changed",
    phrases: ["why was this changed"],
    action: "explain_change_reason",
    description: "Explain rationale for a tracked change from ledger data.",
    offlineCapable: true,
  },
  {
    key: "approve_change",
    phrases: ["approve change"],
    action: "approve_change",
    description: "Approve a pending governance change by id.",
    offlineCapable: true,
  },
  {
    key: "reject_change",
    phrases: ["reject change"],
    action: "reject_change",
    description: "Reject a pending governance change by id.",
    offlineCapable: true,
  },
  {
    key: "rollback_last_approved",
    phrases: ["rollback to last approved"],
    action: "rollback_last_approved",
    description: "Rollback files to the most recent approved snapshot.",
    offlineCapable: true,
  },
  {
    key: "show_change_history",
    phrases: ["show change history"],
    action: "show_change_history",
    description: "Show governance change ledger history.",
    offlineCapable: true,
  },
  {
    key: "set_display_mode_wake_word",
    phrases: ["set display mode wake word"],
    action: "set_display_mode_wake_word",
    description: "Set display interaction mode to wake_word.",
    offlineCapable: true,
  },
  {
    key: "set_display_mode_always_listening",
    phrases: ["set display mode always listening"],
    action: "set_display_mode_always_listening",
    description: "Set display interaction mode to always_listening.",
    offlineCapable: true,
  },
  {
    key: "set_display_mode_typed",
    phrases: ["set display mode typed"],
    action: "set_display_mode_typed",
    description: "Set display interaction mode to typed.",
    offlineCapable: true,
  },
  {
    key: "open_menu",
    phrases: ["open menu"],
    action: "open_menu",
    description: "Open runtime quick menu.",
    offlineCapable: true,
  },
  {
    key: "exit_fullscreen",
    phrases: ["exit fullscreen"],
    action: "exit_fullscreen",
    description: "Exit fullscreen display mode.",
    offlineCapable: true,
  },
  {
    key: "close_program",
    phrases: ["close program"],
    action: "close_program",
    description: "Close local runtime program.",
    offlineCapable: false,
  },
  {
    key: "report_bug",
    phrases: ["report bug"],
    action: "report_bug",
    description: "Open bug reporting flow.",
    offlineCapable: true,
  },
  {
    key: "help",
    phrases: ["help"],
    action: "help",
    description: "Open contextual runtime help.",
    offlineCapable: true,
  },
  {
    key: "add_feature_request",
    phrases: ["add feature request", "log upgrade idea", "add this to updates"],
    action: "add_feature_request",
    description: "Capture a feature/upgrade request into backlog.",
    offlineCapable: true,
  },
  {
    key: "git_backup",
    phrases: ["backup to github", "push to github", "git backup", "commit and push"],
    action: "run_git_backup",
    description: "Commit all changes and push to GitHub for backup.",
    offlineCapable: false,
  },
  {
    key: "show_agent_logs",
    phrases: ["show agent logs", "agent activity", "show manager logs"],
    action: "show_agent_logs",
    description: "Show recent agent activity logs.",
    offlineCapable: true,
  },
  {
    key: "manager_report",
    phrases: ["manager report", "agent status", "show directives"],
    action: "show_manager_report",
    description: "Show manager agent report with directive status.",
    offlineCapable: true,
  },
  {
    key: "gail_approve",
    phrases: ["approve that", "gail approve", "looks good", "sign off on that"],
    action: "gail_approve_first",
    description: "Gail approves the first directive awaiting sign-off.",
    offlineCapable: false,
  },
  {
    key: "gail_reject",
    phrases: ["reject that", "gail reject", "send that back", "not approved"],
    action: "gail_reject_first",
    description: "Gail rejects the first directive awaiting sign-off.",
    offlineCapable: false,
  },
];
